# .github/workflows/release.yml
name: Create Release on Tag

# Trigger only when a tag starting with "v" is pushed
on:
  push:
    tags:
      - 'v*'

# Grant the built-in token rights to create releases and manipulate repo contents
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Create or update the GitHub Release for the pushed tag
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Changes in this release:
            - Version ${{ github.ref_name }} of fortune-teller
          draft: false
          prerelease: false
